author:
  email: example@example.com
  name: John Gorriceta
baseurl: https://example.com
copyright: © John Gorriceta
enablerobotstxt: true
languagecode: en-us
languages:
  en:
    menu:
      main:
      - identifier: home
        name: Home
        url: /
        weight: 10
      - identifier: projects
        name: Projects
        url: /projects/
        weight: 20
      - identifier: about
        name: About
        url: /about/
        weight: 30
      # - identifier: blog
      #   name: Blog
      #   url: /blog/
      #   weight: 30
      # - identifier: categories
      #   name: Categories
      #   url: /categories/
      #   weight: 40
      # - identifier: tags
      #   name: Tags
      #   url: /tags/
      #   weight: 50
      # - identifier: search
      #   name: Search
      #   url: /search/
      #   weight: 60
    title: Designer & Developer
    weight: 1
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
  tableOfContents:
    endLevel: 6
    ordered: true
    startLevel: 2
outputs:
  home:
  - html
  - json
  - rss
paginate: 50
params:
  paige_hide_theme_comment: true
  paige_hide_theme_link: true
permalinks:
  blog: /blog/:year/:month/:day/:title/
social:
  envelope: mailto:johngorriceta1@gmail.com
  # discord: https://discord.com/users/example
  # facebook: https://facebook.com/example
  github: https://github.com/johngthecreator
  # instagram: https://instagram.com/example
  linkedin: https://www.linkedin.com/in/john-gorriceta-9a0918253
  # reddit: https://reddit.com/u/example
  # twitch: https://www.twitch.tv/example
  # twitter: https://twitter.com/example
  # youtube: https://www.youtube.com/user/example
theme: paige
timezone: America/Los_Angeles
titlecasestyle: Go
